POST http://localhost:8000/api/github_projects/
Content-Type: application/json

{
    "name": "testiprojekti2",
    "description": "tämä on testiprojektin kuvaus uuteen projektiin",
    "link": "http://localhost.huuhaa2",
    "rating": 3,
    "owner": 1
}
