PUT http://localhost:8000/api/github_projects/5
Content-Type: application/json

{
    "name": "testiprojekti5",
    "description": "tämä on testiprojektin kuvaus 5",
    "link": "http://localhost.huuhaa5",
    "rating": 2,
    "owner": 1
}